//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class alinanaraclar
    {
        public int alinanaraclarid { get; set; }
        public Nullable<int> alınanarac { get; set; }
        public Nullable<int> aracid { get; set; }
        public Nullable<int> musteriid { get; set; }
    
        public virtual hancars hancars { get; set; }
        public virtual musteriler musteriler { get; set; }
        public virtual hancars hancars1 { get; set; }
    }
}
