//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class arac
    {
        public int alinanaraclarid { get; set; }
        public string isim { get; set; }
        public string soyisim { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public decimal fiyat { get; set; }
    }
}
