//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_8.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class hancars
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public hancars()
        {
            this.alinanaraclar = new HashSet<alinanaraclar>();
            this.alinanaraclar1 = new HashSet<alinanaraclar>();
        }
    
        public int aracid { get; set; }
        public string marka { get; set; }
        public string model { get; set; }
        public Nullable<short> yil { get; set; }
        public Nullable<int> km { get; set; }
        public string yakit { get; set; }
        public string vites { get; set; }
        public string kasatipi { get; set; }
        public string motorgücü { get; set; }
        public string çekiş { get; set; }
        public string durumu { get; set; }
        public Nullable<decimal> Tramer { get; set; }
        public string Renk { get; set; }
        public Nullable<decimal> Fiyat { get; set; }
        public Nullable<int> alınanarac1 { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alinanaraclar> alinanaraclar { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<alinanaraclar> alinanaraclar1 { get; set; }
    }
}
