//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Project_8.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class aracEntities2 : DbContext
    {
        public aracEntities2()
            : base("name=aracEntities2")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<alinanaraclar> alinanaraclar { get; set; }
        public virtual DbSet<hancars> hancars { get; set; }
        public virtual DbSet<musteriler> musteriler { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<arac> arac { get; set; }
    
        public virtual int sp_alterdiagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_alterdiagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_creatediagram(string diagramname, Nullable<int> owner_id, Nullable<int> version, byte[] definition)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var versionParameter = version.HasValue ?
                new ObjectParameter("version", version) :
                new ObjectParameter("version", typeof(int));
    
            var definitionParameter = definition != null ?
                new ObjectParameter("definition", definition) :
                new ObjectParameter("definition", typeof(byte[]));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_creatediagram", diagramnameParameter, owner_idParameter, versionParameter, definitionParameter);
        }
    
        public virtual int sp_cursorhancars()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_cursorhancars");
        }
    
        public virtual int sp_dropdiagram(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_dropdiagram", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagramdefinition_Result> sp_helpdiagramdefinition(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagramdefinition_Result>("sp_helpdiagramdefinition", diagramnameParameter, owner_idParameter);
        }
    
        public virtual ObjectResult<sp_helpdiagrams_Result> sp_helpdiagrams(string diagramname, Nullable<int> owner_id)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_helpdiagrams_Result>("sp_helpdiagrams", diagramnameParameter, owner_idParameter);
        }
    
        public virtual int sp_musterilerkayıtekleme(string visim, string vsoyisim, Nullable<long> vtelno, string vemail, string vadres)
        {
            var visimParameter = visim != null ?
                new ObjectParameter("visim", visim) :
                new ObjectParameter("visim", typeof(string));
    
            var vsoyisimParameter = vsoyisim != null ?
                new ObjectParameter("vsoyisim", vsoyisim) :
                new ObjectParameter("vsoyisim", typeof(string));
    
            var vtelnoParameter = vtelno.HasValue ?
                new ObjectParameter("vtelno", vtelno) :
                new ObjectParameter("vtelno", typeof(long));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vadresParameter = vadres != null ?
                new ObjectParameter("vadres", vadres) :
                new ObjectParameter("vadres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_musterilerkayıtekleme", visimParameter, vsoyisimParameter, vtelnoParameter, vemailParameter, vadresParameter);
        }
    
        public virtual int sp_musterilerkayıtgüncelleme(string visim, string vsoyisim, Nullable<long> vtelno, string vemail, string vadres)
        {
            var visimParameter = visim != null ?
                new ObjectParameter("visim", visim) :
                new ObjectParameter("visim", typeof(string));
    
            var vsoyisimParameter = vsoyisim != null ?
                new ObjectParameter("vsoyisim", vsoyisim) :
                new ObjectParameter("vsoyisim", typeof(string));
    
            var vtelnoParameter = vtelno.HasValue ?
                new ObjectParameter("vtelno", vtelno) :
                new ObjectParameter("vtelno", typeof(long));
    
            var vemailParameter = vemail != null ?
                new ObjectParameter("vemail", vemail) :
                new ObjectParameter("vemail", typeof(string));
    
            var vadresParameter = vadres != null ?
                new ObjectParameter("vadres", vadres) :
                new ObjectParameter("vadres", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_musterilerkayıtgüncelleme", visimParameter, vsoyisimParameter, vtelnoParameter, vemailParameter, vadresParameter);
        }
    
        public virtual int sp_musterilerkayıtsilme()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_musterilerkayıtsilme");
        }
    
        public virtual int sp_renamediagram(string diagramname, Nullable<int> owner_id, string new_diagramname)
        {
            var diagramnameParameter = diagramname != null ?
                new ObjectParameter("diagramname", diagramname) :
                new ObjectParameter("diagramname", typeof(string));
    
            var owner_idParameter = owner_id.HasValue ?
                new ObjectParameter("owner_id", owner_id) :
                new ObjectParameter("owner_id", typeof(int));
    
            var new_diagramnameParameter = new_diagramname != null ?
                new ObjectParameter("new_diagramname", new_diagramname) :
                new ObjectParameter("new_diagramname", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_renamediagram", diagramnameParameter, owner_idParameter, new_diagramnameParameter);
        }
    
        public virtual int sp_upgraddiagrams()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_upgraddiagrams");
        }
    }
}
